### ISSUE TITLE
Error: Conflicting requirements building for DE0-Nano

### ISSUE THREAD

**Issue by MayaPosch** [openrisc/orpsoc-cores#121]
I followed the instructions to add these core files from here: https://github.com/olofk/fusesoc

I then got the following error building the Quartus project:

```
$ fusesoc run de0_nano
ERROR: Conflicting requirements:
Requirements: 'de0_nano == 0-0' <- 'elf__loader >= 0-0'
    +de0_nano-0-0 was ignored because it depends on missing packages
Requirements: 'de0_nano == 0-0'
    Install command rule (+de0_nano-0-0)

Failed to resolve dependencies for ::de0_nano:0
```
I could not find any hints in the FuseSoC documentation or elsewhere on what this error means, or how to resolve it.

**Comment by stffrdhrn** [comment]
This looks similar to the issue I was seeing with https://github.com/fusesoc/fusesoc-cores/issues/10.

The error seems to indicates that **de0_nano cannot be built because elf-loader is missing, or the wrong version** 
I believe this is due to elf-loader being removed recently from fusesoc-cores.  However, if you are using orpsoc-cores the core is still in this project.  So you shouldn't be seeing this issue.

What do you see when you do `fusesoc core-info elf-loader`.

You may also need to do `fusesoc library add elf-loader https://github.com/fusesoc/elf-loader.git`.

**Comment by MayaPosch** [comment]
elf-loader was indeed missing, but it doesn't seem to have made no difference:

```
$ fusesoc run de0_nano
ERROR: Conflicting requirements:
Requirements: 'de0_nano == 0-0' <- 'wb_intercon == 1.0-0'
    +de0_nano-0-0 was ignored because it depends on missing packages
Requirements: 'de0_nano == 0-0'
    Install command rule (+de0_nano-0-0)

Failed to resolve dependencies for ::de0_nano:0
```

I also used the syntax for FuseSoC suggested by the MicroWatt project, but that doesn't work at all:

```
$ fusesoc run --target=de0_nano
usage: fusesoc run [-h] [--no-export] [--build-root BUILD_ROOT] [--setup] [--build] [--run] [--target TARGET] [--tool TOOL] [--flag FLAG] [--system-name SYSTEM_NAME] system ...
fusesoc run: error: the following arguments are required: system, backendargs
```

I have read the FuseSoC documentation many times, and googled for other scraps of information, but I cannot seem to figure out how FuseSoC is supposed to be used. Maybe it is easier to just skip FuseSoC and load the HDL files directly into Quartus based on the core file?

**Comment by MayaPosch** [comment]
Update: I have manually put the HDL files together as per the dependencies in the various .core files and successfully built the SoC in Quartus for the DE0-Nano board. Solving the FuseSoC issue is therefore no longer relevant for me.

Feel free to close this issue.

**Comment by stffrdhrn** [comment]
Thanks for following up.  The second issue seems to be saying that `wb_intercon`, a different module was missing, so you would have had to do a similar `fusesoc library add wb_intercon https...` for that.

Good that you got it all working.

**Comment by Semora** [comment]
I had same problem with `fusesoc run --target=test`:
```
$ fusesoc run --target=test
usage: fusesoc run [-h] [--no-export] [--build-root BUILD_ROOT] [--setup] [--build] [--run] [--target TARGET] [--tool TOOL] [--flag FLAG] [--system-name SYSTEM_NAME] system ...
fusesoc run: error: the following arguments are required: system, backendargs
```
It fixed with 2 changes:
1- Add Core name to the command:
```bash
fusesoc run --target=test fusesoc:examples:blinky:1.0.0
```
You may see following Error before applying next change:
```
ERROR: 'fusesoc:examples:blinky:1.0.0' or any of its dependencies requires 'blinky', but this core was not found
```
2- Run fusesoc command next to `fusesoc.conf`:
```bash
cd YOUR_CORES_ROOT_DIR # Next to fusesoc.conf
fusesoc run --target=test fusesoc:examples:blinky:1.0.0
```
