### ISSUE TITLE
Unable to simulate de0_nano

### ISSUE THREAD

**Issue by jeebujacob** [openrisc/orpsoc-cores#62]
Hello ,
 i m a newbie to openrisc system, got an error trying  to simulate the de0_nano system.

Reference:
jeebu@jeebu:~/openrisc/orpsoc-build$ fusesoc sim --sim=icarus de0_nano

Compiling /home/jeebu/openrisc/orpsoc-build/build/de0_nano/src/elf-loader/elf-loader.c...
Compiling /home/jeebu/openrisc/orpsoc-build/build/de0_nano/src/elf-loader/vpi_wrapper.c...
/usr/bin/iverilog-vpi: 1 file(s) failed to compile.
ERROR: Failed to build simulation model
ERROR: Failed to compile VPI library elf-loader

Thanks in advance.

regards
Jeebu

**Comment by olofk** [comment]
Closing this now due to inactivity. Simulations also work fine for me on de0 nano
