### ISSUE TITLE
Problem while simulating mor1kx-generic

### ISSUE THREAD

**Issue by fjullien** [openrisc/orpsoc-cores#94]
mor1kx-generic depends on wb_intercon-1.0 and wb_bfm-1.0. However, wb_intercon-1.0 depends on wb_bfm for simulation so wb_bfm and wb_bfm-1.0 are present in the build directory before compilation and this lead to an error.

Question is: should we force wb_intercon-1.0 to use wb_bfm-1.0 ? That's the easiest solution here but it may not be always good for every core.

**Comment by fjullien** [comment]
I think the problem is more that fusesoc should not fetch dependencies present in simulator section of sub-core (sub-core means dependencies of the simulated core).

**Comment by olofk** [comment]
I can see both problems and advantages with pulling in the dependencies from the sub-core simulator section, but I think we should keep it for now until it has been analyzed in more detail.

I did however push some commits to hopefully fix the problem you were seeing. It would be great if you could try to rerun the simulation and see if it works now

**Comment by olofk** [comment]
Reported working. Closing this
